/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package st10456656_prog6112_exam;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class MovieTicketsForm extends javax.swing.JFrame {

    /**
     * Creates new form MovieTicketsForm
     */
    public MovieTicketsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbxMovieSelection = new javax.swing.JComboBox<>();
        jtxtNumberOfTickets = new javax.swing.JTextField();
        jtxtTicketPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAreaTicketReport = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMIExitReport = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIProcessReport = new javax.swing.JMenuItem();
        JMIClearFields = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOVIE TICKETS");
        setName("MOVIE TICKETS"); // NOI18N

        jLabel1.setText("MOVIE:");

        jLabel2.setText("NUMBER OF TICKETS:");

        jLabel3.setText("TICKET PRICE:");

        jLabel4.setText("TICKET REPORT:");

        jcbxMovieSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Napoleon", "Oppenheimer", "Damsel" }));
        jcbxMovieSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxMovieSelectionActionPerformed(evt);
            }
        });

        jtxtNumberOfTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberOfTicketsActionPerformed(evt);
            }
        });

        jtxtTicketPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTicketPriceActionPerformed(evt);
            }
        });

        jtxtAreaTicketReport.setColumns(20);
        jtxtAreaTicketReport.setRows(5);
        jScrollPane1.setViewportView(jtxtAreaTicketReport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jcbxMovieSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxtNumberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbxMovieSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNumberOfTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        JMIExitReport.setText("Exit");
        JMIExitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIExitReportActionPerformed(evt);
            }
        });
        jMenu1.add(JMIExitReport);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMIProcessReport.setText("Process");
        jMIProcessReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIProcessReportActionPerformed(evt);
            }
        });
        jMenu2.add(jMIProcessReport);

        JMIClearFields.setText("Clear");
        JMIClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIClearFieldsActionPerformed(evt);
            }
        });
        jMenu2.add(JMIClearFields);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxMovieSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxMovieSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxMovieSelectionActionPerformed

    private void jtxtNumberOfTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberOfTicketsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberOfTicketsActionPerformed

    private void jtxtTicketPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTicketPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTicketPriceActionPerformed

     static File file = new File("C:\\Users\\lab_services_student\\Documents\\report.txt");

    public static void writeToFile(String movieNme, String loc, double movieTicketPri, double numOfTick, double totalTicketPri) {
        //Method to write the name, age and price into a text file, each value in a seperate row.
        
        //check if file does not exists
        if (!file.exists()) {
            try {
                //create the file if it does not exist
                file.createNewFile();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error creating the file");
            }
        }
        Scanner input = new Scanner(System.in);
        try {
            FileWriter fw = new FileWriter(file, true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("MOVIE TICKET REPORT");
            bw.newLine();
            bw.write("*******************************");
            bw.newLine();
            bw.write("MOVIE NAME: "+ movieNme);
            bw.newLine();
            bw.write("MOVIE TICKET PRICE: "+ movieTicketPri);
            //bw.write(Integer.toString(ag));
            bw.newLine();
            bw.write("NUMBER OF TICKETS: " +numOfTick);
            bw.newLine();
            bw.write("TOTAL TICKET PRICE: R "+totalTicketPri);
            bw.newLine();
            bw.write("*******************************");
            //BufferedWriter 
            //bw.write(Double.toString(pri));
            bw.newLine();
            bw.close();
            fw.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error writing to file");
        }
    }
    private void jMIProcessReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIProcessReportActionPerformed
        
        String movieName = (String) jcbxMovieSelection.getSelectedItem();
        int numberOfTickets = Integer.parseInt(jtxtNumberOfTickets.getText());
        double priceOfTicket = Double.parseDouble(jtxtTicketPrice.getText());
        double totalTickets = numberOfTickets * priceOfTicket;
        double vatOnTicket = priceOfTicket * (14/100);
        double totalMovieTicketPrice = totalTickets + (vatOnTicket)  ;
        
        //create output text
        String output = "MOVIE NAME: " + movieName;
        output += "\nMOVIE TICKET PRICE: R" + priceOfTicket;
        output += "\nNUMBER OF TICKETS: " + numberOfTickets ;
        output += "\nTOTAL TICKET PRICE : R" + totalMovieTicketPrice + "\n";
        
        
        jtxtAreaTicketReport.append(output);
    }//GEN-LAST:event_jMIProcessReportActionPerformed

    private void JMIExitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIExitReportActionPerformed
        //code to exit program
        System.exit(0);
    }//GEN-LAST:event_JMIExitReportActionPerformed

    private void JMIClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIClearFieldsActionPerformed
        //code to clear everything
        jtxtNumberOfTickets.setText(" ");
        jtxtTicketPrice.setText(" ");
        jtxtAreaTicketReport.setText(" ");
       
    }//GEN-LAST:event_JMIClearFieldsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicketsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicketsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicketsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicketsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicketsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIClearFields;
    private javax.swing.JMenuItem JMIExitReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMIProcessReport;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbxMovieSelection;
    private javax.swing.JTextArea jtxtAreaTicketReport;
    private javax.swing.JTextField jtxtNumberOfTickets;
    private javax.swing.JTextField jtxtTicketPrice;
    // End of variables declaration//GEN-END:variables
}
